# Generated by Django 5.0.6 on 2024-05-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_nick',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ник в телеграмм'),
        ),
    ]
