# Generated by Django 5.0.6 on 2024-05-26 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('time', models.DateTimeField(verbose_name='время выполнения привычки')),
                ('action', models.CharField(choices=[('walk', 'гулять'), ('drink', 'пить воду'), ('workout', 'заниматься спортом'), ('learn', 'изучать новое')], max_length=100, verbose_name='действие')),
                ('good_habit', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('period', models.CharField(choices=[('two_hours', 'каждые 2 часа'), ('dayly', 'ежедневно'), ('weekly', 'еженедельно')], default='weekly', max_length=30, verbose_name='периодичность выполнения')),
                ('award', models.CharField(blank=True, max_length=150, null=True, verbose_name='вознаграждение')),
                ('lead_time', models.IntegerField(verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель привычки')),
            ],
        ),
    ]
