# Generated by Django 5.0.6 on 2024-05-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'verbose_name': 'привычка', 'verbose_name_plural': 'привычки'},
        ),
        migrations.AlterField(
            model_name='habit',
            name='lead_time',
            field=models.IntegerField(verbose_name='время на выполнение секунд'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('two_hours', 'каждые 2 часа'), ('daily', 'ежедневно'), ('weekly', 'еженедельно')], default='weekly', max_length=30, verbose_name='периодичность выполнения'),
        ),
    ]
