# Generated by Django 5.0.6 on 2024-05-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('daily', 'ежедневно'), ('two_days', 'каждые 2 дня'), ('weekly', 'еженедельно')], default='weekly', max_length=30, verbose_name='периодичность выполнения'),
        ),
    ]
